#!/usr/bin/with-contenv bash

# make our folders
mkdir -p /config/.config/BISQ && \
mkdir -p /config/.config/BISQ/webserver_data
# set webserver port on first install
#[[ ! -f /config/.config/BISQ/webserver_data/server-config.txt ]] && \
#    echo "port 8081" > /config/.config/BISQ/webserver_data/server-config.txt

sed -i 's|"password":"abc",|"password":"kjhbouygiuvhgvghv",|' /gclient/app.js
sed -i "s#process.env.PASSWORD || 'abc';#process.env.PASSWORD || 'kjhbouygiuvhgvghv';#" /gclient/maketoken.js
if ([ -n "$GUAC_USER" ] || [ -n "$GUAC_PASS" ]) && [ -z "$PASSWORD" ]; then
    echo '
********************************************************
********************************************************
****                                                ****
****  GUAC_USER and GUAC_PASS vars are deprecated   ****
****                                                ****
****  Temporary credentials are being set:          ****
****                                                ****
****  User: abc                                     ****
****  Pass: abc                                     ****
****                                                ****
****                                                ****
****  See the readme for new credential info        ****
****                                                ****
****                                                ****
********************************************************
********************************************************'
elif ([ -n "$USER" ] || [ -n "$PASSWORD" ]); then
    echo "${USER}:${PASSWORD}" | chpasswd
    echo "Setting user and password from environment variable."
else 
    echo "abc:kjhbouygiuvhgvghv" | chpasswd
    echo "No password is set for the interface - please check ASAP and set one in environment vars"
fi

# permissions
chown -R ${USER}:${USER} \
    /config \
    /opt/BISQ
